-- Instalação completa, sem inserir dados de exemplo.
-- Para banco existente, prefira migracao_auth.sql.
begin;
-- ============================================================
-- ESTOQUE TI - SCRIPT COMPLETO DO SUPABASE
-- Execute no Supabase em: SQL Editor > New query > Run
-- ============================================================

-- ============================================================
-- 1. TABELA PRINCIPAL
-- ============================================================

create table if not exists public.estoque (
    id bigint generated by default as identity primary key,
    patrimonio varchar(7) not null unique,
    nome varchar(120) not null,
    categoria varchar(40) not null,
    status varchar(30) not null default 'Disponível',
    responsavel varchar(120),
    descricao varchar(500),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint estoque_patrimonio_formato_check
        check (patrimonio ~ '^[0-9]{5,7}$'),

    constraint estoque_categoria_check
        check (categoria in (
            'Notebook',
            'Desktop',
            'Monitor',
            'Servidor',
            'Switch',
            'Roteador',
            'Impressora',
            'Nobreak',
            'Periférico',
            'Outro'
        )),

    constraint estoque_status_check
        check (status in (
            'Disponível',
            'Em Uso',
            'Manutenção',
            'Descarte'
        ))
);

-- Caso a tabela estoque já existisse em uma versão anterior do projeto,
-- garante que a coluna usada pela versão atual também exista.
alter table public.estoque
    add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_estoque_patrimonio
    on public.estoque (patrimonio);

create index if not exists idx_estoque_categoria
    on public.estoque (categoria);

create index if not exists idx_estoque_status
    on public.estoque (status);

create index if not exists idx_estoque_created_at
    on public.estoque (created_at desc);

-- ============================================================
-- 2. TABELA DE HISTÓRICO
-- ============================================================

create table if not exists public.estoque_historico (
    id bigint generated by default as identity primary key,
    estoque_id bigint,
    patrimonio varchar(7),
    acao varchar(20) not null,
    campo_alterado varchar(100),
    valor_antigo text,
    valor_novo text,
    usuario_email text,
    criado_em timestamptz not null default now(),

    constraint historico_acao_check
        check (acao in ('CRIACAO', 'EDICAO', 'EXCLUSAO'))
);

create index if not exists idx_historico_estoque_id
    on public.estoque_historico (estoque_id);

create index if not exists idx_historico_criado_em
    on public.estoque_historico (criado_em desc);

-- ============================================================
-- 3. FUNÇÃO PARA ATUALIZAR updated_at
-- ============================================================

create or replace function public.fn_atualizar_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_estoque_updated_at on public.estoque;

create trigger trg_estoque_updated_at
before update on public.estoque
for each row
execute function public.fn_atualizar_updated_at();

-- ============================================================
-- 4. FUNÇÃO DE HISTÓRICO
-- ============================================================

create or replace function public.fn_log_estoque_historico()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    usuario text;
begin
    usuario := coalesce(auth.jwt() ->> 'email', 'sistema');

    if tg_op = 'INSERT' then
        insert into public.estoque_historico (
            estoque_id,
            patrimonio,
            acao,
            campo_alterado,
            valor_antigo,
            valor_novo,
            usuario_email
        )
        values (
            new.id,
            new.patrimonio,
            'CRIACAO',
            null,
            null,
            new.nome,
            usuario
        );

        return new;
    end if;

    if tg_op = 'UPDATE' then
        if new.patrimonio is distinct from old.patrimonio then
            insert into public.estoque_historico
            (estoque_id, patrimonio, acao, campo_alterado, valor_antigo, valor_novo, usuario_email)
            values
            (new.id, new.patrimonio, 'EDICAO', 'Patrimônio', old.patrimonio, new.patrimonio, usuario);
        end if;

        if new.nome is distinct from old.nome then
            insert into public.estoque_historico
            (estoque_id, patrimonio, acao, campo_alterado, valor_antigo, valor_novo, usuario_email)
            values
            (new.id, new.patrimonio, 'EDICAO', 'Nome', old.nome, new.nome, usuario);
        end if;

        if new.categoria is distinct from old.categoria then
            insert into public.estoque_historico
            (estoque_id, patrimonio, acao, campo_alterado, valor_antigo, valor_novo, usuario_email)
            values
            (new.id, new.patrimonio, 'EDICAO', 'Categoria', old.categoria, new.categoria, usuario);
        end if;

        if new.status is distinct from old.status then
            insert into public.estoque_historico
            (estoque_id, patrimonio, acao, campo_alterado, valor_antigo, valor_novo, usuario_email)
            values
            (new.id, new.patrimonio, 'EDICAO', 'Status', old.status, new.status, usuario);
        end if;

        if new.responsavel is distinct from old.responsavel then
            insert into public.estoque_historico
            (estoque_id, patrimonio, acao, campo_alterado, valor_antigo, valor_novo, usuario_email)
            values
            (new.id, new.patrimonio, 'EDICAO', 'Responsável', old.responsavel, new.responsavel, usuario);
        end if;

        if new.descricao is distinct from old.descricao then
            insert into public.estoque_historico
            (estoque_id, patrimonio, acao, campo_alterado, valor_antigo, valor_novo, usuario_email)
            values
            (new.id, new.patrimonio, 'EDICAO', 'Descrição', old.descricao, new.descricao, usuario);
        end if;

        return new;
    end if;

    if tg_op = 'DELETE' then
        insert into public.estoque_historico (
            estoque_id,
            patrimonio,
            acao,
            campo_alterado,
            valor_antigo,
            valor_novo,
            usuario_email
        )
        values (
            old.id,
            old.patrimonio,
            'EXCLUSAO',
            null,
            old.nome,
            null,
            usuario
        );

        return old;
    end if;

    return null;
end;
$$;

drop trigger if exists trg_estoque_historico on public.estoque;

create trigger trg_estoque_historico
after insert or update or delete on public.estoque
for each row
execute function public.fn_log_estoque_historico();


-- Para o banco existente: execute este arquivo no SQL Editor do Supabase.
-- Não exclui equipamentos nem histórico. Pode ser executado novamente.

alter table public.estoque enable row level security;
alter table public.estoque_historico enable row level security;

-- Remove privilégios públicos e mantém somente as operações usadas pelo app.
revoke all on table public.estoque, public.estoque_historico from public, anon, authenticated;
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.estoque to authenticated;
grant select on public.estoque_historico to authenticated;

-- Uma política restritiva também limita políticas permissivas antigas.
-- Contas anônimas do Auth não são usuários autorizados deste sistema.
drop policy if exists "estoque_exige_sessao" on public.estoque;
create policy "estoque_exige_sessao" on public.estoque
as restrictive for all to public
using (auth.uid() is not null and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false)
with check (auth.uid() is not null and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false);

drop policy if exists "historico_exige_sessao" on public.estoque_historico;
create policy "historico_exige_sessao" on public.estoque_historico
as restrictive for all to public
using (auth.uid() is not null and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false)
with check (auth.uid() is not null and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false);

drop policy if exists "estoque_select_authenticated" on public.estoque;
drop policy if exists "estoque_insert_authenticated" on public.estoque;
drop policy if exists "estoque_update_authenticated" on public.estoque;
drop policy if exists "estoque_delete_authenticated" on public.estoque;
drop policy if exists "historico_select_authenticated" on public.estoque_historico;
create policy "estoque_select_authenticated" on public.estoque for select to authenticated using (true);
create policy "estoque_insert_authenticated" on public.estoque for insert to authenticated with check (true);
create policy "estoque_update_authenticated" on public.estoque for update to authenticated using (true) with check (true);
create policy "estoque_delete_authenticated" on public.estoque for delete to authenticated using (true);
create policy "historico_select_authenticated" on public.estoque_historico for select to authenticated using (true);

-- Somente a sequência do estoque precisa ser acessível ao cliente.
do $$
declare seq text;
begin
  seq := pg_get_serial_sequence('public.estoque', 'id');
  if seq is not null then
    execute format('revoke all on sequence %s from public, anon, authenticated', seq);
    execute format('grant usage, select on sequence %s to authenticated', seq);
  end if;
  seq := pg_get_serial_sequence('public.estoque_historico', 'id');
  if seq is not null then
    execute format('revoke all on sequence %s from public, anon, authenticated', seq);
  end if;
end $$;


commit;
